### PR TITLE
Custom port functionality

### PR DESCRIPTION
**Pull request by gnakul2001**
## Scope
Added the functionality for custom port configuration

### Screenshots
image

---

### Developer checklist
- [x] I’ve manually tested that code works locally on desktop and mobile browsers.
- [x] I’ve reviewed my code.
- [x] I’ve removed all my personal credentials (API keys etc.) from the code.

### CODE REVIEW

**Comment by kaustubh-s1** [comment]
Hi @gnakul2001 thanks for the PR! 

The port that would need changing is the port on which the command `functions_framework` is running (8080 by default). 8080 is a very common port and might be active for some other application that user might have left open. For this we want to give an option to change this if he wants or keep 8080 bu default if he doesn't mention the flag `--port`

You have changed the port for the localhost:4000 which is for the frontend of bot UI. We don't need to change that as the backend is communicating at that port.

Can you try and implement this?

**Comment by gnakul2001** [comment]
Sure, on it.

**Comment by gnakul2001** [comment]
@kaustubh-s1 done, please verify.

**Comment by kaustubh-s1** [comment]
Can you share a screenshot of the cli after running test command. If you enter the port as let's say 8082, the link in blue color reflect that change?

**Comment by gnakul2001** [comment]
image


Text in blue and Running on http://127.0.0.1:8082 both done

**Comment by gnakul2001** [comment]
image

Also accessible on web.

**Comment by kaustubh-s1** [comment]
Can you go to the long blue link and see if the bot is working fine

**Comment by kaustubh-s1** [comment]
Hi @gnakul2001 Actually I just realized that we don't need to store the port in an env and pass it to `server.py`, there's a simpler way to go about this. If you look closely at [this](https://github.com/cofactoryai/textbase/blob/f6d73d9898d849f66ceafe208e85c789a64fdea5/textbase/utils/server.py#L36) in `server.py` file, it is just printing out the final URL, nothing else. And in this line we are adding the encoded URL which has `port 8080`, this can be avoided by simply printing this line in `textbase_cli.py` itself. 

Because the server.py is just starting the server at port 4000 and setting it up for serving build files at this URL while communicating with 8080.

Try this-
Replce the code for `test` command in `textbase_cli.py` with this one-
```py
@cli.command()
@click.option("--path", prompt="Path to the main.py file", required=True)
@click.option("--port", default=8080, help="Port number for the server")
def test(path, port):
    server_path = importlib.resources.files('textbase').joinpath('utils', 'server.py')
    try:
        if os.name == 'posix':
            process_local_ui = subprocess.Popen(f'python3 {server_path}', shell=True)
        else:
            process_local_ui = subprocess.Popen(f'python {server_path}', shell=True)

        process_gcp = subprocess.Popen(f'functions_framework --target=on_message --source={path} --port={port} --debug',
                     shell=True,
                     stdin=subprocess.PIPE)

        click.secho(f"Server URL: http://localhost:4000/?API_URL=http%3A%2F%2Flocalhost%3A{port}", fg='cyan', bold=True)
        process_local_ui.communicate()
        process_gcp.communicate()  # Wait for the process to finish
    except KeyboardInterrupt:
        process_gcp.kill()  # Stop the process when Ctrl+C is pressed
        process_local_ui.kill()
        click.secho("Server stopped.", fg='red')
```

add `import urllib.parse` in imports

Also replace `server.py` with this-
```py
import os
import http.server
import socketserver
from textbase.utils.download_build import download_and_extract_zip

socketserver.TCPServer.allow_reuse_address=True

# URL of the zip file containing the dist folder
zip_url = "https://storage.googleapis.com/chatbot_mainpy/frontendUI.zip"

# Destination folder where the zip file will be extracted
destination_folder = os.path.join(os.getcwd(), "")

# Download and extract the zip file
download_and_extract_zip(zip_url, destination_folder)

# Port where the HTTP server will be running
PORT = 4000

class MyHandler(http.server.SimpleHTTPRequestHandler):
    def translate_path(self, path):
        path = super().translate_path(path)
        relpath = os.path.relpath(path, os.getcwd())
        fullpath = os.path.join(os.getcwd(), 'dist', relpath)
        return fullpath

Handler = MyHandler

# Change the current working directory to the destination folder
os.chdir(destination_folder)

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    httpd.serve_forever()
```
Do these changes and you will see what I mean.


Once you confirm this is working in your machine, edit these changes, push them and we'll be good to merge this PR 🚀@

Thanks

**Comment by gnakul2001** [comment]
But what if we encounter a problem when starting our server using server.py? It will still print the Server URL even if it doesn't start.

**Comment by kaus-cofactory** [comment]
Why will we need to start server.py specifically?
it does nothing but load the UI to localhost, we want that to be done on test command. See this whole package is on PyPI as `textbase-client` - https://pypi.org/project/textbase-client/

So the users would be using this library directly like this- `textbase-client test` and that spins up the local UI on the local server.

There is no need to load server.py individually.

**Comment by kaustubh-s1** [comment]
Why will we need to start server.py specifically?
it does nothing but load the UI to localhost, we want that to be done on test command. See this whole package is on PyPI as `textbase-client` - https://pypi.org/project/textbase-client/

So the users would be using this library directly like this- `textbase-client test` and that spins up the local UI on the local server.

There is no need to load server.py individually.

**Comment by gnakul2001** [comment]
Yes, I think I can add some more error handling here. I will add that in other PR.

But this is fine what you suggested to do.

**Comment by gnakul2001** [comment]
image

**Comment by gnakul2001** [comment]
I have pushed the fix.

This is my another PR https://github.com/cofactoryai/textbase/pull/104. Please have a look to that too.

**Comment by kaus-cofactory** [comment]
@gnakul2001 just do these changes and your PR is good to be merged after final review 🚀
Screenshot 2023-09-04 at 12 44 14 PM

**Comment by gnakul2001** [comment]
Done with this change
image

**Review by kaus-cofactory — CHANGES_REQUESTED** [review]
change line 21 to this-
`@click.option("--port", default=8080, help="Port number for the server")`

this will automatically take 8080 as the default port and only on the flag --port you can change it.
Also docs need to be updated for this feature. Can you do that here - https://github.com/cofactoryai/textbase/blob/main/docs/docs/usage.md

**Comment by gnakul2001** [comment]
@kaus-cofactory help= will not ask for the port. See the screenshot I attached.
image

**Comment by kaus-cofactory** [comment]
> @kaus-cofactory help= will not ask for the port. See the screenshot I attached. image

Ok i see, then just update the docs here- https://github.com/cofactoryai/textbase/blob/main/docs/docs/usage.md
with proper info of whatever changes you made

**Comment by kaus-cofactory** [comment]
@gnakul2001 in the docs mention that if you leave this part empty it will automatically take in 8080 as the port.
Screenshot 2023-09-04 at 1 19 42 PM


Also specify that this is important because 8080 is a very commonly used port and you might have it open somewhere for any other application, to avoid that this flag can help you change the port for the backend server

**Comment by kaustubh-s1** [comment]
@gnakul2001 can you also mention that if you leave this part empty it will automatically take in 8080 as the port, as I said in the above comment

**Comment by gnakul2001** [comment]
image
Done @kaustubh-s1

**Comment by kaustubh-s1** [comment]
LGTM, @bharatchhabraai can you approve this!

**Review by bharatchhabraai — APPROVED** [review]

**Review by kaus-cofactory — APPROVED** [review]

**Pull request merged**
