### PR TITLE
Functionalities added to Textbase

### PR DESCRIPTION
**Pull request by NeerajSati**
Three features or corrections are made:
1. Empty input field cannot be submitted (It was possible earlier)
2. Code optimized by making a single submit function to handle send message
3. Dark mode option added

### CODE REVIEW

**Comment by kaus-cofactory** [comment]
Hi @NeerajSati, thanks for doing these changes. Can you quickly show a screenshot for the following changes. Thanks!

**Comment by NeerajSati** [comment]
I had created a video explaining the changes done. 
https://drive.google.com/file/d/1p7zlrPQIhI-piWJ_p5imPEonKmPHq7cg/view?usp=sharing

**Comment by kaus-cofactory** [comment]
Cool, also there have been some changes in the frontend part of the library. Can you do a git pull and then add your edits accordingly to resolve the conflicts?

**Comment by NeerajSati** [comment]
I have resolved the merge conflicts and created a new merged build.

**Comment by kaus-cofactory** [comment]
All good now! Thanks for this @NeerajSati 🙌🏻

**Pull request merged**
