### PR TITLE
Improved error handling

### PR DESCRIPTION
**Pull request by gnakul2001**
## Scope
Improved error handling to enhance troubleshooting during chatbot setup.

### Screenshots
image
image
image

---

### Developer checklist
- [x] I’ve manually tested that code works locally on desktop and mobile browsers.
- [x] I’ve reviewed my code.
- [x] I’ve removed all my personal credentials (API keys etc.) from the code.

### CODE REVIEW

**Comment by kaustubh-s1** [comment]
@gnakul2001 Hi, once again, good work on this one. Before we can test and merge this, can you resolve the merge conflicts and push again.

**Comment by gnakul2001** [comment]
@kaustubh-s1 resolved the conflicts. Please review this.

**Comment by gnakul2001** [comment]
Hi @kaustubh-s1 Please review this PR.

**Comment by kaustubh-s1** [comment]
Yes @gnakul2001 lgtm, thanks for this 🙌🏻

**Review by kaustubh-s1 — APPROVED** [review]

**Comment by gnakul2001** [comment]
@kaustubh-s1 Can we connect over discord DM. I have sent you a message.

**Pull request merged**
