### PR TITLE
Integrated features to recommend movies to watch on your next flight!

### PR DESCRIPTION
**Pull request by SirArthur7**
Synopsis-
- I have made changes to 2 files- main.py, model.py. 
- I have used 2 free APIs that are readily available and have low latency- TimeTable Lookup API, The Movie Database (TMDb).
- I have added 2 features for movie recommendation and flight detail guide that are up to date and not based on old data that GPT3.5 was trained on. The 2 features can be used in tandem or separately as well, and it still retains its original GPT conversation style.
- I have also tried to make it fair and not generate hallucinated content.
- I have worked according to the default logic facilitating easy merging/replacement without much changes, but have also not changed any original code. 
- It requires only 1 package installation of- xmltodict (can easily be done by pip or can be integrated into poetry)

Detailed summary-
1. main.py - I have commented default generate() function and used my generate_custom() function that has been defined in the model.py file and accepts the same parameters as the original generate() function
2. model.py - I have added 2 utility functions to handle API calls that can be easily added into a new utils.py file and imported here, but for sake of not changing code drastically I haven't done that. I have also written the code for generate_custom() function that implements function calling using the 2 util functions based on the prompt.

### CODE REVIEW

**Comment by kaus-cofactory** [comment]
@SirArthur7 Thanks for this great example usecase. I really appreciate it. Just have a few requested edits if you would want to help us out further.
I can see you are using OpenAI function calling. However, we want to keep the `models.py` to be a generic codebase. Here are a few suggestions:
- Can you refactor the code such that we have your `main.py` inside a new folder `examples` in the root directory. 
Something like this => `examples/openai-function-call/main.py`. Do not delete the original `main.py` from the root directory, just paste your altered main.py into this place.
- Whatever changes you have made in the `models.py` should be such that any user can use the function calling thing just like he does the normal GPT call. You have to refactor it to make it a general-purpose thing and not just for movie recommendations. 
- You can keep all the functions/attributes related to movie recommendation in the `main.py` and keep the openai function calls in the `models.py`, this way other users in the future can directly use via `models`.
I hope this makes sense.

It would also be great if you can provide more documentation about implementation into maybe a `.md` file inside here `examples/openai-function-call/`

**Comment by SirArthur7** [comment]
Hi Kaustubh,
It's not just a standalone use case, that's why the title reads,
"Integrated features", because if you look at the system prompt, and my new
generate() function, you'll see that it doesn't forget that it's a generic
chatbot, and it will behave just like your default GPT model and you may
ask it anything else and it would answer. I simply enriched it's info base
with up-to-date info about flights and movies. And you may use any
combination of those 2 features-
1. Just chat about movies
2. Just chat about flight details
3. Chat about both flights and movies
Also I wrote the custom_generate() in model.py in such a way that you could
simply replace your old generate() and no one would even notice a
difference except for it being informed of movies and flights after 2021.
I have no issues in making the changes you mentioned, would love to
contribute in a nice way, but I wanted you to understand my line of
thinking before you suggest the changes.
So knowing this now, should I still do what you've asked for, or do you
want to do it differently?

Thanks,
Anannyo Dey
JU BCSE

**Comment by kaus-cofactory** [comment]
Thanks @SirArthur7, @silasalberti and I talked about this the other day and we want to keep the library's `models.py` separate from all the other things. It should contain only classes for each different type of model integration like for OpenAI GPT, Huggingface, OpenAI Function Call. Any other changes should not be a part of this file. 

I can see you have added functions like `def flight_info()` and `def movie_recommendation()` inside the `models.py`, while it's all good but as said above we want to keep `models.py` clean and modular only for integrations.

However I do believe that what you have implemented can be used by users anytime and its a very good example of what's possible with `textbase`, so we plan to move all such things (and the `main.py` that people edited) inside a `examples` folder such that in future when we make a separate docs website, we can include your contributions there to be referred by others. 

And if we do want to use your usecase its as simple as replacing the path of the `main.py` in the command to `poetry run python textbase/textbase_cli.py test examples/openai_function-call/main.py`. I hope this makes sense and why modularity and structuring things like this aligns with our long term vision 😃

If you do the changes please do a `git pull` as somethings have been changed in the `main branch`

**Comment by kaus-cofactory** [comment]
closing because of inactivity. If you want to work on it again, just @ me and will open

**Pull request closed without merging**
