### PR TITLE
Added features and documentation

### PR DESCRIPTION
**Pull request by nini0309**
1. Added option between 3 APIs and 1 library i.e. OpenAI, HuggingFace, Botlibre, HuggingFaceLibrary
2. Created documentation

### CODE REVIEW

**Comment by kaus-cofactory** [comment]
Hi, this is good. Can you go through this PR [here](https://github.com/cofactoryai/textbase/pull/2) and see if things overlap. If there's something additional, you can modify it accordingly. Some things have been changed the codebase so make sure to do a `git pull` before doing changes.

**Comment by nini0309** [comment]
Hi @kaus-cofactory do I also add my main.py file in the examples folder? If yes, what do I name the subfolder?

**Comment by kaus-cofactory** [comment]
yes, you would have to add your `main.py` inside the `examples/` directory but there is already exists one `examples/hugingface/main.py`, so I think that's already done. If you have something to add on to it or a new folder for any new example apart from huggingface, you can create the folder with the appropriate name

**Comment by nini0309** [comment]
Thanks @kaus-cofactory Where do I push the documentation I've created? Currently it is in a md file inside a docs folder

**Comment by kaus-cofactory** [comment]
You can add it inside the folder that you would create. Like this-
`examples/your_folder_name/docs.md`

**Comment by nini0309** [comment]
Hey @kaus-cofactory I've pushed the changes

**Comment by kaus-cofactory** [comment]
This is quite nice. Can you also share a video/gif of the whole working?

**Comment by nini0309** [comment]
Sure, heres the video https://youtu.be/r-HIBJ9guQw
For the demo I had used a single main.py file

**Comment by kaus-cofactory** [comment]
The docs.md in both folder have the same content. I guess it makes more sense to either remove one of those or modify the content such that it fits only the the details of that folder. So botlibre docs should not have any info regarding openai or huggingface.

**Comment by nini0309** [comment]
I've made the changes @kaus-cofactory

**Comment by kaus-cofactory** [comment]
@nini0309 perfect. Thank you so much for this ✨

**Pull request merged**
