### PR TITLE
features added: customization panel, mulitmedia support, voice input

### PR DESCRIPTION
**Pull request by HarshS1611**
# ChatBot Customizer

A modern chatbot with a flair for personalization and multimedia interaction.

## Video Demo

https://www.loom.com/share/64ab5e9584f143918dabf3bf418b4e09?sid=0ff31799-403a-4308-b813-76a67421e035

## Features

1. **Customization Panel** - Change the aesthetics to match your vibe.
    - Set background colors.
    - Customize font colors.
    - Choose from a range of font styles, including Georgia and Times New Roman.

2. **Avatar Selection** - Represent yourself with an image of your choice.

3. **Multimedia Interaction**:
    - Upload images directly.
    - Extract text from images using the OCR API - https://rapidapi.com/apishub/api/ocr-100-image-text-extractor
    - Get immediate responses to your queries.

4. **Code Interaction using voice input** - Input Python code and execute it.

## How to Use
1. Launch the chatbot.
2. Open the customization panel to tweak the appearance.
3. Interact with the bot. Upload images, ask for assistance, or simply chat!

## Contributions

Contributions are welcome! Please read the contribution guidelines and make sure to check out the pull request template.

### CODE REVIEW

**Comment by kaus-cofactory** [comment]
One more thing @HarshS1611 so right now in the chat background you can change the color, mostly to a solid color. We've been thinking if its also possible to add more depth to it and let the user to configure the background just like Instagram or Whatsapp lets users do it. Like having multiple options like gradients, images, etc

For example-
Screenshot 2023-08-15 at 2 04 00 AM

Do you think this can be done? If yes, please let us know your thoughts on it

**Comment by HarshS1611** [comment]
Thanks for the feedback, I have tried to give more customized background colors and also added a feature to add a background image of the user's choice. One thing about that "Upload Image" option is that if we select any image file then only the button shows "Upload Image" otherwise it shows "Send" to send the user input through chat. Hope you like it.
Screenshot 2023-08-15 030726
Screenshot 2023-08-15 021723

**Comment by kaus-cofactory** [comment]
@HarshS1611 This is perfect, thank you so much for helping with this 🙌🏻. One small thing, we do not want to lose the dark theme option. So can you make a separate button on the right side of the dark theme button for all these background task?

**Comment by HarshS1611** [comment]
Hey @kaus-cofactory , I have done the required changes. Now you will be able to change the theme and also customize it using the customization panel. Hope you like it.
Screenshot 2023-08-15 120140
Screenshot 2023-08-15 120124

**Comment by kaus-cofactory** [comment]
That was fast @HarshS1611. Thanks for all the help ✨

**Pull request merged**
