### PR TITLE
React Animation

### PR DESCRIPTION
**Pull request by anto-mervin**
Resolved the Animation with commits

### CODE REVIEW

**Comment by kaustubh-s1** [comment]
Can you also provide like a short video/gif of how the changes look on the UI

**Comment by anto-mervin** [comment]
[Click Here](https://youtu.be/XSzPPxsteWs) to see the animation video

**Comment by kaus-cofactory** [comment]
Hey @anto-mervin, looks good. Does it work the same with the text generated by the API in response?
Can you confirm this?

**Comment by anto-mervin** [comment]
Yes it work in api response also

**Comment by kaus-cofactory** [comment]
@Sidharth-Sethi can you quickly check if this works fine with our current structure?

**Pull request closed without merging**
